-- MySQL Script generated by MySQL Workbench
-- 10/26/15 17:29:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema BookDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BookDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BookDB` DEFAULT CHARACTER SET utf8 ;
USE `BookDB` ;

-- -----------------------------------------------------
-- Table `BookDB`.`Author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookDB`.`Author` (
  `AuthorID` CHAR(5) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Age` INT UNSIGNED NULL,
  `country` VARCHAR(45) NULL,
  PRIMARY KEY (`AuthorID`),
  UNIQUE INDEX `AuthorID_UNIQUE` (`AuthorID` ASC),
  UNIQUE INDEX `Age_UNIQUE` (`Age` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BookDB`.`Book`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BookDB`.`Book` (
  `ISBN` CHAR(13) NOT NULL,
  `Title` VARCHAR(45) NULL,
  `AuthorID` CHAR(5) NULL,
  `Publisher` VARCHAR(45) NULL,
  `PublishDate` DATETIME NULL,
  `Price` FLOAT UNSIGNED NULL,
  `Author_AuthorID` CHAR(5) NOT NULL,
  PRIMARY KEY (`ISBN`),
  UNIQUE INDEX `PublishDate_UNIQUE` (`PublishDate` ASC),
  UNIQUE INDEX `ISBN_UNIQUE` (`ISBN` ASC),
  INDEX `fk_Book_Author_idx` (`Author_AuthorID` ASC),
  CONSTRAINT `fk_Book_Author`
    FOREIGN KEY (`Author_AuthorID`)
    REFERENCES `BookDB`.`Author` (`AuthorID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
